definitions:
  models.NotFountResponse:
    properties:
      msg:
        type: string
    type: object
  models.UserCreateSchema:
    properties:
      age:
        type: integer
      email:
        type: string
      lastname:
        type: string
      name:
        type: string
    type: object
  models.UserResponse:
    properties:
      age:
        type: integer
      email:
        type: string
      id:
        type: string
      lastname:
        type: string
      name:
        type: string
    type: object
  models.UserUpdateSchema:
    properties:
      age:
        type: integer
      email:
        type: string
      lastname:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserCreateSchema'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.NotFountResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.NotFountResponse'
      summary: Create a new user
      tags:
      - users
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.NotFountResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.NotFountResponse'
      summary: Delete user by ID
      tags:
      - users
      - users
    get:
      consumes:
      - application/json
      description: Get user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.NotFountResponse'
      summary: Get user by ID
      tags:
      - users
      - users
    patch:
      consumes:
      - application/json
      description: Partially update an existing user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserUpdateSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.NotFountResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.NotFountResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.NotFountResponse'
      summary: Partially update an existing user
      tags:
      - users
      - users
    put:
      consumes:
      - application/json
      description: Update an existing user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserUpdateSchema'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.NotFountResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.NotFountResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.NotFountResponse'
      summary: Update an existing user
      tags:
      - users
      - users
swagger: "2.0"
