definitions:
  models.NotFountResponse:
    properties:
      msg:
        type: string
    type: object
  models.User:
    properties:
      age:
        type: integer
      email:
        type: string
      id:
        type: string
      lastname:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Get user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.NotFountResponse'
      summary: Get user by ID
      tags:
      - users
      - users
swagger: "2.0"
